if (isDedicated) exitWith {};
private["_Lightbar"];
_veh_l = _this select 0;
_Lightbar = "Jonzie_Lightbar" createVehicleLocal [0,0,100];
_distance = 0;_height = 0;_LeftRight = 0;_type = typeOf _veh_l;
switch (_type) do
{
	case "Jonzie_Charger": {_height = _height + 1.434;_distance = _distance + -0.4;_LeftRight = _LeftRight + 0;};
	case "Jonzie_Charger_PD": {_height = _height + 1.434;_distance = _distance + -0.4;_LeftRight = _LeftRight + 0;};
};
_Lightbar attachTo [_veh_l,[_LeftRight,_distance,_height]];
_Blue_Lightsource = "Jonzie_Light_Blue" createVehicleLocal [0,0,100];
_Red_Lightsource = "Jonzie_Light_Blue" createVehicleLocal [0,0,100];
_Blue_Tex = "#(argb,8,8,3)color(0,0,1,1.0,co)";
_Blue_rvmat = "a3\data_f\lights\car_beacon_blue_emit.rvmat";
_Red_Tex = "#(argb,8,8,3)color(0,0,1,1.0,co)";
_Red_rvmat = "a3\data_f\lights\car_beacon_blue_emit.rvmat";
_Off_Tex = "jonzie_carpack\universal_cars\tex\glass.paa";
_Off_rvmat = "a3\data_f\default_alpha.rvmat";
while {alive _veh_l} do
{
	if (_veh_l animationPhase "secondary" == 1 && getdammage _veh_l < 0.9) then
	{
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Blue_Tex];
		_Lightbar setObjectMaterial [8,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [8,_Off_Tex];
		_Lightbar setObjectMaterial [8,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Red_Tex];
		_Lightbar setObjectMaterial [9,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [9,_Off_Tex];
		_Lightbar setObjectMaterial [9,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [20,_Blue_Tex];
		_Lightbar setObjectMaterial [20,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [20,_Off_Tex];
		_Lightbar setObjectMaterial [20,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Blue_Tex];
		_Lightbar setObjectMaterial [10,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Off_Tex];
		_Lightbar setObjectMaterial [10,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Blue_Tex];
		_Lightbar setObjectMaterial [10,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Off_Tex];
		_Lightbar setObjectMaterial [10,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Blue_Tex];
		_Lightbar setObjectMaterial [10,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Off_Tex];
		_Lightbar setObjectMaterial [10,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Blue_Tex];
		_Lightbar setObjectMaterial [10,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Off_Tex];
		_Lightbar setObjectMaterial [10,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Blue_Tex];
		_Lightbar setObjectMaterial [10,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [10,_Off_Tex];
		_Lightbar setObjectMaterial [10,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Red_Tex];
		_Lightbar setObjectMaterial [11,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [11,_Off_Tex];
		_Lightbar setObjectMaterial [11,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [22,_Blue_Tex];
		_Lightbar setObjectMaterial [22,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [22,_Off_Tex];
		_Lightbar setObjectMaterial [22,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [12,_Red_Tex];
		_Lightbar setObjectMaterial [12,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [12,_Off_Tex];
		_Lightbar setObjectMaterial [12,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [14,_Blue_Tex];
		_Lightbar setObjectMaterial [14,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [14,_Off_Tex];
		_Lightbar setObjectMaterial [14,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [17,_Red_Tex];
		_Lightbar setObjectMaterial [17,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [17,_Off_Tex];
		_Lightbar setObjectMaterial [17,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [16,_Blue_Tex];
		_Lightbar setObjectMaterial [16,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [16,_Off_Tex];
		_Lightbar setObjectMaterial [16,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [17,_Red_Tex];
		_Lightbar setObjectMaterial [17,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [17,_Off_Tex];
		_Lightbar setObjectMaterial [17,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [16,_Blue_Tex];
		_Lightbar setObjectMaterial [16,_Blue_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [-0.33, 0, -0.01] ];
		sleep 0.07;
		_Lightbar setobjecttexture [16,_Off_Tex];
		_Lightbar setObjectMaterial [16,_Off_rvmat];
		_Blue_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
		_Lightbar setobjecttexture [19,_Red_Tex];
		_Lightbar setObjectMaterial [19,_Red_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0.33, 0, -0.01] ];	
		sleep 0.07;
		_Lightbar setobjecttexture [19,_Off_Tex];
		_Lightbar setObjectMaterial [19,_Off_rvmat];
		_Red_Lightsource attachTo [_Lightbar, [0, 0, -100000] ];
		sleep 0.07;
	} 
	else 
	{
	waitUntil {(_veh_l animationPhase "secondary" == 1 && getdammage _veh_l < 0.9)};
	};
	waitUntil {(_veh_l animationPhase "secondary" == 1 && getdammage _veh_l < 0.9)};
};