if (isDedicated) exitWith {};
private["_veh_l"];
_veh_l = _this select 0;
_Orange_Tex = "#(argb,8,8,3)color(1,0.501961,0,1.0,co)";
_Orange_rvmat = "a3\data_f\lights\car_beacon_orange_emit.rvmat";
_Off_Tex = "jonzie_carpack\universal_cars\tex\glass.paa";
_Off_rvmat = "a3\data_f\default_alpha.rvmat";
while {alive _veh_l} do
{
	if (_veh_l animationPhase "Switch_4" == 0 && _veh_l animationPhase "Switch_5" == 1 && getdammage _veh_l < 0.9) then//Right
	{
		_veh_l setobjecttexture [25,_Orange_Tex];
		_veh_l setObjectMaterial [25,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [26,_Orange_Tex];
		_veh_l setObjectMaterial [26,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [27,_Orange_Tex];
		_veh_l setObjectMaterial [27,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [28,_Orange_Tex];
		_veh_l setObjectMaterial [28,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [29,_Orange_Tex];
		_veh_l setObjectMaterial [29,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [30,_Orange_Tex];
		_veh_l setObjectMaterial [30,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [31,_Orange_Tex];
		_veh_l setObjectMaterial [31,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [32,_Orange_Tex];
		_veh_l setObjectMaterial [32,_Orange_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [25,_Off_Tex];
		_veh_l setObjectMaterial [25,_Off_rvmat];
		_veh_l setobjecttexture [26,_Off_Tex];
		_veh_l setObjectMaterial [26,_Off_rvmat];
		_veh_l setobjecttexture [27,_Off_Tex];
		_veh_l setObjectMaterial [27,_Off_rvmat];
		_veh_l setobjecttexture [28,_Off_Tex];
		_veh_l setObjectMaterial [28,_Off_rvmat];
		_veh_l setobjecttexture [29,_Off_Tex];
		_veh_l setObjectMaterial [29,_Off_rvmat];
		_veh_l setobjecttexture [30,_Off_Tex];
		_veh_l setObjectMaterial [30,_Off_rvmat];
		_veh_l setobjecttexture [31,_Off_Tex];
		_veh_l setObjectMaterial [31,_Off_rvmat];
		_veh_l setobjecttexture [32,_Off_Tex];
		_veh_l setObjectMaterial [32,_Off_rvmat];
		sleep 0.25;
	};
	if (_veh_l animationPhase "Switch_5" == 0 && _veh_l animationPhase "Switch_4" == 1 && getdammage _veh_l < 0.9) then//Left
	{
		_veh_l setobjecttexture [32,_Orange_Tex];
		_veh_l setObjectMaterial [32,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [31,_Orange_Tex];
		_veh_l setObjectMaterial [31,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [30,_Orange_Tex];
		_veh_l setObjectMaterial [30,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [29,_Orange_Tex];
		_veh_l setObjectMaterial [29,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [28,_Orange_Tex];
		_veh_l setObjectMaterial [28,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [27,_Orange_Tex];
		_veh_l setObjectMaterial [27,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [26,_Orange_Tex];
		_veh_l setObjectMaterial [26,_Orange_rvmat];			
		sleep 0.25;
		_veh_l setobjecttexture [25,_Orange_Tex];
		_veh_l setObjectMaterial [25,_Orange_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [32,_Off_Tex];
		_veh_l setObjectMaterial [32,_Off_rvmat];
		_veh_l setobjecttexture [31,_Off_Tex];
		_veh_l setObjectMaterial [31,_Off_rvmat];
		_veh_l setobjecttexture [30,_Off_Tex];
		_veh_l setObjectMaterial [30,_Off_rvmat];
		_veh_l setobjecttexture [29,_Off_Tex];
		_veh_l setObjectMaterial [29,_Off_rvmat];
		_veh_l setobjecttexture [28,_Off_Tex];
		_veh_l setObjectMaterial [28,_Off_rvmat];
		_veh_l setobjecttexture [27,_Off_Tex];
		_veh_l setObjectMaterial [27,_Off_rvmat];
		_veh_l setobjecttexture [26,_Off_Tex];
		_veh_l setObjectMaterial [26,_Off_rvmat];
		_veh_l setobjecttexture [25,_Off_Tex];
		_veh_l setObjectMaterial [25,_Off_rvmat];
		sleep 0.25;
	};
	if (_veh_l animationPhase "Switch_5" == 1 && _veh_l animationPhase "Switch_4" == 1 && getdammage _veh_l < 0.9) then//Hazz
	{
		_veh_l setobjecttexture [28,_Orange_Tex];
		_veh_l setObjectMaterial [28,_Orange_rvmat];
		_veh_l setobjecttexture [29,_Orange_Tex];
		_veh_l setObjectMaterial [29,_Orange_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [27,_Orange_Tex];
		_veh_l setObjectMaterial [27,_Orange_rvmat];
		_veh_l setobjecttexture [30,_Orange_Tex];
		_veh_l setObjectMaterial [30,_Orange_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [26,_Orange_Tex];
		_veh_l setObjectMaterial [26,_Orange_rvmat];
		_veh_l setobjecttexture [31,_Orange_Tex];
		_veh_l setObjectMaterial [31,_Orange_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [25,_Orange_Tex];
		_veh_l setObjectMaterial [25,_Orange_rvmat];
		_veh_l setobjecttexture [32,_Orange_Tex];
		_veh_l setObjectMaterial [32,_Orange_rvmat];
		sleep 0.25;
		_veh_l setobjecttexture [28,_Off_Tex];
		_veh_l setObjectMaterial [28,_Off_rvmat];
		_veh_l setobjecttexture [29,_Off_Tex];
		_veh_l setObjectMaterial [29,_Off_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [27,_Off_Tex];
		_veh_l setObjectMaterial [27,_Off_rvmat];
		_veh_l setobjecttexture [30,_Off_Tex];
		_veh_l setObjectMaterial [30,_Off_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [26,_Off_Tex];
		_veh_l setObjectMaterial [26,_Off_rvmat];
		_veh_l setobjecttexture [31,_Off_Tex];
		_veh_l setObjectMaterial [31,_Off_rvmat];		
		sleep 0.25;
		_veh_l setobjecttexture [25,_Off_Tex];
		_veh_l setObjectMaterial [25,_Off_rvmat];
		_veh_l setobjecttexture [32,_Off_Tex];
		_veh_l setObjectMaterial [32,_Off_rvmat];
		sleep 0.25;		
	};	
	waitUntil {(_veh_l animationPhase "Switch_5" == 1 && getdammage _veh_l < 0.9 or _veh_l animationPhase "Switch_4" == 1 && getdammage _veh_l < 0.9 or _veh_l animationPhase "Switch_5" == 1 && _veh_l animationPhase "Switch_4" == 1 && getdammage _veh_l < 0.9)};
};